--- 
clone: 
  depth: 1
kind: pipeline
name: azrimPipeline
steps: 
  - 
    environment: 
      TG_TOKEN: 
        from_secret: TOKEN
      CHANNEL_ID:
        from_secret: CHATID
    commands: 
      - "bash build_script.sh"
    image: azrim89/kernel:latest
    name: Build
